from __future__ import annotations

import re
import sqlite3
from pathlib import Path
from typing import Any, Iterable, Optional
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit


POSTGRES_SCHEMES = ("postgres://", "postgresql://")


def is_postgres_dsn(target: object) -> bool:
    text = str(target or "").strip().lower()
    return text.startswith(POSTGRES_SCHEMES)


def sanitize_postgres_dsn(raw_dsn: object) -> str:
    text = str(raw_dsn or "").strip()
    if not text:
        raise ValueError("PostgreSQL 连接串不能为空")

    parsed = urlsplit(text)
    scheme = "postgresql"
    query_items = [
        (key, value)
        for key, value in parse_qsl(parsed.query, keep_blank_values=True)
        if str(key or "").strip().lower() != "directconnection"
    ]
    path = parsed.path or ""
    if not path or path == "/":
        path = "/postgres"

    return urlunsplit((scheme, parsed.netloc, path, urlencode(query_items), parsed.fragment))


def resolve_db_target(raw_target: object, *, root_dir: Path, default_path: Path) -> str:
    text = str(raw_target or "").strip()
    if not text:
        return str(Path(default_path).resolve())
    if is_postgres_dsn(text):
        return sanitize_postgres_dsn(text)

    path = Path(text).expanduser()
    if not path.is_absolute():
        path = (Path(root_dir) / path).resolve()
    return str(path)


def normalize_db_cache_key(target: object) -> str:
    text = str(target or "").strip()
    if not text:
        return ""
    if is_postgres_dsn(text):
        return sanitize_postgres_dsn(text)
    try:
        return str(Path(text).expanduser().resolve())
    except Exception:
        return text


def db_target_exists(target: object) -> bool:
    text = str(target or "").strip()
    if not text:
        return False
    if is_postgres_dsn(text):
        return True
    return Path(text).expanduser().exists()


def db_target_supports_file_backup(target: object) -> bool:
    return not is_postgres_dsn(target)


def ensure_sqlite_parent_dir(target: object) -> None:
    if db_target_supports_file_backup(target):
        Path(str(target)).expanduser().parent.mkdir(parents=True, exist_ok=True)


def db_target_name(target: object, fallback: str = "database") -> str:
    text = str(target or "").strip()
    if not text:
        return fallback
    if is_postgres_dsn(text):
        parsed = urlsplit(sanitize_postgres_dsn(text))
        db_name = parsed.path.lstrip("/") or "postgres"
        return f"{db_name}.sql"
    return Path(text).name or fallback


class CompatRow:
    def __init__(self, columns: list[str], values: Iterable[Any]):
        self._columns = list(columns)
        self._values = tuple(values)
        self._mapping = {name: self._values[index] for index, name in enumerate(self._columns)}

    def __getitem__(self, key: object) -> Any:
        if isinstance(key, int):
            return self._values[key]
        return self._mapping[str(key)]

    def __iter__(self):
        return iter(self._values)

    def __len__(self) -> int:
        return len(self._values)

    def get(self, key: object, default: Any = None) -> Any:
        return self._mapping.get(str(key), default)

    def keys(self):
        return self._mapping.keys()

    def items(self):
        return self._mapping.items()

    def values(self):
        return self._mapping.values()


class MemoryCursor:
    def __init__(self, rows: Optional[list[Any]] = None, *, lastrowid: Optional[int] = None):
        self._rows = list(rows or [])
        self._index = 0
        self.lastrowid = lastrowid
        self.rowcount = len(self._rows)

    def fetchone(self):
        if self._index >= len(self._rows):
            return None
        row = self._rows[self._index]
        self._index += 1
        return row

    def fetchall(self):
        if self._index <= 0:
            self._index = len(self._rows)
            return list(self._rows)
        remaining = self._rows[self._index :]
        self._index = len(self._rows)
        return remaining

    def close(self) -> None:
        return None


def _rewrite_postgres_ddl(sql: str) -> str:
    rewritten = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
        flags=re.IGNORECASE,
    )
    rewritten = re.sub(r"\bAUTOINCREMENT\b", "", rewritten, flags=re.IGNORECASE)
    return rewritten


def _translate_qmark_placeholders(sql: str) -> str:
    result: list[str] = []
    in_single = False
    in_double = False
    i = 0
    while i < len(sql):
        char = sql[i]
        if char == "'" and not in_double:
            if in_single and i + 1 < len(sql) and sql[i + 1] == "'":
                result.append("''")
                i += 2
                continue
            in_single = not in_single
            result.append(char)
            i += 1
            continue
        if char == '"' and not in_single:
            in_double = not in_double
            result.append(char)
            i += 1
            continue
        if char == "?" and not in_single and not in_double:
            result.append("%s")
            i += 1
            continue
        result.append(char)
        i += 1
    return "".join(result)


def _build_pragma_table_info_rows(conn: Any, table_name: str) -> list[tuple[Any, ...]]:
    cursor = conn.cursor()
    cursor.execute(
        """
        SELECT
            ordinal_position - 1 AS cid,
            column_name,
            data_type,
            CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,
            column_default,
            CASE WHEN position('nextval' in COALESCE(column_default, '')) > 0 THEN 1 ELSE 0 END AS pk
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = %s
        ORDER BY ordinal_position
        """,
        (str(table_name or "").strip(),),
    )
    rows = cursor.fetchall()
    cursor.close()
    return [tuple(row) for row in rows]


def _parse_special_postgres_sql(conn: Any, sql: str) -> Optional[MemoryCursor]:
    normalized = str(sql or "").strip().rstrip(";")
    lowered = normalized.lower()

    if lowered in {"pragma journal_mode=wal", "pragma synchronous=normal"}:
        return MemoryCursor([])

    pragma_match = re.match(r"^pragma\s+table_info\(([^)]+)\)$", lowered, flags=re.IGNORECASE)
    if pragma_match:
        table_name = pragma_match.group(1).strip().strip("'\"")
        return MemoryCursor(_build_pragma_table_info_rows(conn, table_name))

    return None


class PostgresCursorWrapper:
    def __init__(self, cursor: Any, *, lastrowid: Optional[int] = None):
        self._cursor = cursor
        self.lastrowid = lastrowid
        self.rowcount = getattr(cursor, "rowcount", -1)

    def _wrap_rows(self, rows: list[Any]) -> list[Any]:
        if not rows:
            return []
        description = getattr(self._cursor, "description", None) or []
        columns = [str(item.name) for item in description]
        if not columns:
            return list(rows)
        return [CompatRow(columns, row) for row in rows]

    def fetchone(self):
        row = self._cursor.fetchone()
        if row is None:
            return None
        return self._wrap_rows([row])[0]

    def fetchall(self):
        rows = self._cursor.fetchall()
        return self._wrap_rows(rows)

    def close(self) -> None:
        self._cursor.close()


class PostgresConnectionWrapper:
    def __init__(self, dsn: str):
        try:
            import psycopg
        except ImportError as exc:
            raise RuntimeError("当前环境未安装 psycopg，请先安装 psycopg[binary]") from exc

        self._psycopg = psycopg
        self._dsn = sanitize_postgres_dsn(dsn)
        self._conn = psycopg.connect(self._dsn, connect_timeout=10)
        self.row_factory = None

    def _try_fetch_lastrowid(self) -> Optional[int]:
        try:
            with self._conn.cursor() as cursor:
                savepoint_name = "sp_lastrowid_fetch"
                cursor.execute(f"SAVEPOINT {savepoint_name}")
                try:
                    cursor.execute("SELECT LASTVAL()")
                    row = cursor.fetchone()
                    cursor.execute(f"RELEASE SAVEPOINT {savepoint_name}")
                except Exception:
                    cursor.execute(f"ROLLBACK TO SAVEPOINT {savepoint_name}")
                    cursor.execute(f"RELEASE SAVEPOINT {savepoint_name}")
                    return None
                if not row:
                    return None
                return int(row[0])
        except Exception:
            return None

    def execute(self, sql: str, params: Optional[Iterable[Any]] = None):
        special = _parse_special_postgres_sql(self._conn, sql)
        if special is not None:
            return special

        translated_sql = _translate_qmark_placeholders(_rewrite_postgres_ddl(sql))
        if translated_sql.strip().lower() == "begin immediate":
            translated_sql = "BEGIN"

        cursor = self._conn.cursor()
        if params is None:
            cursor.execute(translated_sql)
        else:
            cursor.execute(translated_sql, tuple(params))

        lastrowid = None
        lowered = translated_sql.lstrip().lower()
        if lowered.startswith("insert into") and " returning " not in lowered:
            lastrowid = self._try_fetch_lastrowid()
        return PostgresCursorWrapper(cursor, lastrowid=lastrowid)

    def executemany(self, sql: str, seq_of_params: Iterable[Iterable[Any]]):
        special = _parse_special_postgres_sql(self._conn, sql)
        if special is not None:
            return special

        translated_sql = _translate_qmark_placeholders(_rewrite_postgres_ddl(sql))
        cursor = self._conn.cursor()
        cursor.executemany(translated_sql, [tuple(item) for item in seq_of_params])
        return PostgresCursorWrapper(cursor)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            if exc_type is None:
                self.commit()
            else:
                self.rollback()
        finally:
            self.close()
        return False


def connect_db(target: object):
    text = str(target or "").strip()
    if is_postgres_dsn(text):
        return PostgresConnectionWrapper(text)
    conn = sqlite3.connect(text)
    conn.row_factory = sqlite3.Row
    return conn
